language: nodejs
nodejs:
    - 7

sudo: required
services:
    - docker

before_install:
    - docker build -t "$DOCKER_ID"/complex-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true "$DOCKER_ID"/complex-test npm test -- --coverage 

after_success:
    - docker build -t "$DOCKER_ID"/complex-client ./client
    - docker build -t "$DOCKER_ID"/complex-nginx ./nginx
    - docker build -t "$DOCKER_ID"/complex-server ./server
    - docker build -t "$DOCKER_ID"/complex-worker ./worker
    # Login to Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to Docker
    - docker push "$DOCKER_ID"/complex-client
    - docker push "$DOCKER_ID"/complex-nginx
    - docker push "$DOCKER_ID"/complex-server
    - docker push "$DOCKER_ID"/complex-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "eu-central-1"
    app: "complex"
    env: "Complex-env"
    bucket_name: "elasticbeanstalk-eu-central-1-613636068067"
    bucket_path: "complex"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY